MANIFEST_DESC = {
    'a_clear_text': {'title': 'Clear text traffic is Enabled For App<br>[android:usesCleartextTraffic=true]',
                     'level': 'high',
                     'description': 'app打算使用明文网络流量,如明文HTTP、FTP栈,DownloadManager和媒体播放器。默认值为应用目标API级别27或低是“真实的”。目标应用程序API级别28或更高版本默认为“false”。避免明文传输的关键原因是缺乏机密性、真实性、和保护篡改;攻击者可以窃听网络传输数据没有被发现并修改它。',
                     'name': 'Clear text traffic is Enabled For App [android:usesCleartextTraffic=true]'},
    'a_boot_aware': {'title': 'App is direct-boot aware <br>[android:directBootAware=true]', 'level': 'info',
                     'description': '这个程序可以运行在用户解锁装置。如果您正在使用一个自定义子类的应用程序中,如果在您的应用程序直接引导意识到任何组件,然后整个定制的应用程序被认为是直接引导意识。在直接启动,应用程序只能访问存储在设备保护存储的数据。',
                     'name': 'App is direct-boot aware [android:directBootAware=true]'},
    'a_network_sec': {'title': 'App has a Network Security Configuration<br>[android:networkSecurityConfig]',
                      'level': 'info',
                      'description': '网络安全配置功能允许应用程序定制他们的网络安全设置在一个安全的、声明式配置文件无需修改应用程序代码。可以配置这些设置为特定的域和一个特定的应用程序。',
                      'name': 'App has a Network Security Configuration [android:networkSecurityConfig]'},
    'a_debuggable': {'title': 'Debug Enabled For App<br>[android:debuggable=true]', 'level': 'high',
                     'description': '调试是启用应用程序使逆向工程师更容易钩调试器。这使得倾销和访问堆栈跟踪调试助手类。',
                     'name': 'Debug Enabled For App [android:debuggable=true]'},
    'a_allowbackup': {'title': 'Application Data can be Backed up<br>[android:allowBackup=true]', 'level': 'medium',
                      'description': '这个标志允许任何人通过亚行备份应用程序数据。它允许用户启用USB调试复制应用程序数据的设备。',
                      'name': 'Application Data can be Backed up [android:allowBackup=true]'},
    'a_allowbackup_miss': {'title': 'Application Data can be Backed up<br>[android:allowBackup] flag is missing.',
                           'level': 'medium',
                           'description': '国旗(android: allowBackup)应设置为false。默认情况下,它设置为true,允许任何人通过亚行备份应用程序数据。它允许用户启用USB调试复制应用程序数据的设备。',
                           'name': 'Application Data can be Backed up [android:allowBackup] flag is missing.'},
    'a_testonly': {'title': 'Application is in Test Mode <br>[android:testOnly=true]', 'level': 'high',
                   'description': '它可能暴露功能或数据本身以外的会导致安全漏洞。',
                   'name': 'Application is in Test Mode [android:testOnly=true]'},
    'a_taskaffinity': {'title': 'TaskAffinity is set for Activity </br>(%s)', 'level': 'high',
                       'description': '如果taskAffinity设置,那么其他应用程序可以读取意图送到活动属于另一个任务。总是使用默认设置保持亲和力的包名称,以防止敏感信息在发送或接收意图由另一个应用程序读取。',
                       'name': 'TaskAffinity is set for Activity'},
    'a_launchmode': {'title': 'Launch Mode of Activity (%s) is not standard.', 'level': 'high',
                     'description': '活动不应该有发射模式属性设置为“singleTask / singleInstance”成为根活动和其他应用程序有可能读的内容调用意图。所以它需要使用“标准”发射模式属性当敏感信息包含在一个意图。',
                     'name': 'Launch Mode of Activity is not standard.'},
    'a_prot_sign': {'title': '<strong>%s</strong> (%s) is Protected by a permission.</br>%s<br>[android:exported=true]',
                    'level': 'info',
                    'description': '找到出口,但受权限保护。',
                    'name': 'is Protected by a permission.[android:exported=true]'}, 'a_prot_normal': {
        'title': '<strong>%s</strong> (%s) is Protected by a permission, but the protection level of the permission should be checked.</br>%s <br>[android:exported=true]',
        'level': 'high',
        'description': '共享与其他应用程序在设备上,因此可以访问其他应用程序在设备上。这是受权限保护。然而,权限设置的保护水平正常。这意味着一个恶意的应用程序可以请求并获得许可并与组件交互。如果是设置签名,只有应用程序使用相同的证书才能获得许可。',
        'name': 'is Protected by a permission, but the protection level of the permission should be checked.[android:exported=true]'},
    'a_prot_danger': {
        'title': '<strong>%s</strong> (%s) is Protected by a permission, but the protection level of the permission should be checked.</br>%s <br>[android:exported=true]',
        'level': 'high',
        'description': '共享与其他应用程序在设备上,因此可以访问其他应用程序在设备上。这是受权限保护。然而,保护级别的权限设置为危险。这意味着一个恶意的应用程序可以请求并获得许可并与组件交互。如果是设置签名,只有应用程序使用相同的证书才能获得许可。',
        'name': 'is Protected by a permission, but the protection level of the permission should be checked.[android:exported=true]'},
    'a_prot_sign_sys': {
        'title': '<strong>%s</strong> (%s) is Protected by a permission, but the protection level of the permission should be checked.</br>%s <br>[android:exported=true]',
        'level': 'info',
        'description': '是找到出口,但受权限保护。然而,权限设置为signatureOrSystem的保护水平。建议使用签名的水平。签名水平应该满足大多数场合,不依赖于设备上的应用程序安装。',
        'name': 'is Protected by a permission, but the protection level of the permission should be checked.[android:exported=true]'},
    'a_prot_unknown': {
        'title': '<strong>%s</strong> (%s) is Protected by a permission, but the protection level of the permission should be checked.</br>%s <br>[android:exported=true]',
        'level': 'high',
        'description': '共享与其他应用程序在设备上,因此可以访问其他应用程序在设备上。它是保护许可不是分析中定义应用程序。因此,许可的保护水平应检查定义。如果它被设置为正常或危险,恶意的应用程序可以请求和获得许可和与组件交互。如果它被设置签名,只有应用程序使用相同的证书才能获得许可。',
        'name': 'is Protected by a permission, but the protection level of the permission should be checked.[android:exported=true]'},
    'a_prot_normal_appl': {
        'title': '<strong>%s</strong> (%s) is Protected by a permission at the application level, but the protection level of the permission should be checked.</br>%s <br>[android:exported=true]',
        'level': 'high',
        'description': '共享与其他应用程序在设备上,因此可以访问其他应用程序在设备上。它是允许在应用程序级别的保护。然而,权限设置的保护水平正常。这意味着一个恶意的应用程序可以请求并获得许可并与组件交互。如果是设置签名,只有应用程序使用相同的证书才能获得许可。',
        'name': 'is Protected by a permission at the application level, but the protection level of the permission should be checked.[android:exported=true]'},
    'a_prot_danger_appl': {
        'title': '<strong>%s</strong> (%s) is Protected by a permission at the application level, but the protection level of the permission should be checked.</br>%s <br>[android:exported=true]',
        'level': 'high',
        'description': '共享与其他应用程序在设备上,因此可以访问其他应用程序在设备上。它是允许在应用程序级别的保护。然而,保护级别的权限设置为危险。这意味着一个恶意的应用程序可以请求并获得许可并与组件交互。如果是设置签名,只有应用程序使用相同的证书才能获得许可。',
        'name': 'is Protected by a permission at the application level, but the protection level of the permission should be checked.[android:exported=true]'},
    'a_prot_sign_appl': {
        'title': '<strong>%s</strong> (%s)  Protected by a permission at the application level.</br>%s<br>[android:exported=true]',
        'level': 'info',
        'description': '是找到出口,但允许在应用程序级别的保护。',
        'name': 'Protected by a permission at the application level.[android:exported=true]'}, 'a_prot_sign_sys_appl': {
        'title': '<strong>%s</strong> (%s) is Protected by a permission at the application level, but the protection level of the permission should be checked.</br>%s <br>[android:exported=true]',
        'level': 'info',
        'description': '是找到出口,但允许在应用程序级别的保护。然而,权限设置为signatureOrSystem的保护水平。建议使用签名的水平。签名水平应该满足大多数场合,不依赖于设备上的应用程序安装。',
        'name': 'is Protected by a permission at the application level, but the protection level of the permission should be checked.[android:exported=true]'},
    'a_prot_unknown_appl': {
        'title': '<strong>%s</strong> (%s) is Protected by a permission at the application, but the protection level of the permission should be checked.</br>%s <br>[android:exported=true]',
        'level': 'high',
        'description': '共享与其他应用程序在设备上,因此可以访问其他应用程序在设备上。它是受权限保护在应用程序级别分析应用程序中没有定义。因此,许可的保护水平应检查定义。如果它被设置为正常或危险,恶意的应用程序可以请求和获得许可和与组件交互。如果它被设置签名,只有应用程序使用相同的证书才能获得许可。',
        'name': 'is Protected by a permission at the application, but the protection level of the permission should be checked.[android:exported=true]'},
    'a_not_protected': {'title': '<strong>%s</strong> (%s) is not Protected. <br>[android:exported=true]',
                        'level': 'high',
                        'description': '公有组件能被任何应用程序的任何组件所访问，这容易造成安全问题。 导出的Activity组件能被第三方APP任意调用，攻击者可构造恶意payload进行攻击，导致敏感信息泄露，并可能受到绕过认证、恶意代码注入等攻击风险。',
                        'name': 'is not Protected. [android:exported=true]'},
    'a_not_protected_filter': {'title': '<strong>%s</strong> (%s) is not Protected.<br>An intent-filter exists.',
                               'level': 'high',
                               'description': '公有组件能被任何应用程序的任何组件所访问，这容易造成安全问题。 ',
                               'name': 'is not Protected.An intent-filter exists.'}, 'c_not_protected': {
        'title': '<strong>%s</strong> (%s) is not Protected. <br>[[Content Provider, targetSdkVersion < 17]',
        'level': 'high',
        'description': '共享与其他应用程序在设备上,因此可以访问其他应用程序在设备上。这个内容提供者的目标一个API级别17岁以下,这使得它在默认情况下,出口无论API级别的系统上运行的应用程序。',
        'name': 'is not Protected.[[Content Provider, targetSdkVersion < 17]'}, 'c_not_protected2': {
        'title': '<strong>%s</strong> (%s) would not be Protected if the application ran on a device where the the API level was less than 17. <br>[Content Provider, targetSdkVersion >= 17]',
        'level': 'high',
        'description': '内容提供者将出口如果API的应用程序在设备上运行水平低于17。在这种情况下,它将与其他应用程序共享设备因此离开它可以访问任何其他应用程序在设备上。',
        'name': 'would not be Protected if the application ran on a device where the the API level was less than 17.[Content Provider, targetSdkVersion >= 17]'},
    'c_prot_normal': {
        'title': '<strong>%s</strong> (%s) is Protected by a permission, but the protection level of the permission should be checked.</br>%s <br>[Content Provider, targetSdkVersion < 17]',
        'level': 'high',
        'description': '共享与其他应用程序在设备上,因此可以访问其他应用程序在设备上。这是受权限保护。然而,权限设置的保护水平正常。这意味着一个恶意的应用程序可以请求并获得许可并与组件交互。如果是设置签名,只有应用程序使用相同的证书才能获得许可。',
        'name': 'is Protected by a permission, but the protection level of the permission should be checked.[Content Provider, targetSdkVersion < 17]'},
    'c_prot_danger': {
        'title': '<strong>%s</strong> (%s) is Protected by a permission, but the protection level of the permission should be checked.</br>%s <br>[Content Provider, targetSdkVersion < 17]',
        'level': 'high',
        'description': '共享与其他应用程序在设备上,因此可以访问其他应用程序在设备上。这是受权限保护。然而,保护级别的权限设置为危险。这意味着一个恶意的应用程序可以请求并获得许可并与组件交互。如果是设置签名,只有应用程序使用相同的证书才能获得许可。',
        'name': 'is Protected by a permission, but the protection level of the permission should be checked.[Content Provider, targetSdkVersion < 17]'},
    'c_prot_sign': {
        'title': '<strong>%s</strong> (%s) is Protected by a permission.</br>%s <br>[Content Provider, targetSdkVersion < 17]',
        'level': 'info',
        'description': '共享与其他应用程序在设备上,因此可以访问其他应用程序在设备上。它是保护许可。',
        'name': 'is Protected by a permission.[Content Provider, targetSdkVersion < 17]'}, 'c_prot_sign_sys': {
        'title': '<strong>%s</strong> (%s) is Protected by a permission, but the protection level of the permission should be checked.</br>%s <br>[Content Provider, targetSdkVersion < 17]',
        'level': 'info',
        'description': '找到出口,但受权限保护。然而,权限设置为signatureOrSystem的保护水平。建议使用签名的水平。签名水平应该满足大多数场合,不依赖于设备上的应用程序安装。',
        'name': 'is Protected by a permission, but the protection level of the permission should be checked.[Content Provider, targetSdkVersion < 17]'},
    'c_prot_unknown': {
        'title': '<strong>%s</strong> (%s) is Protected by a permission, but the protection level of the permission should be checked.</br>%s <br>[Content Provider, targetSdkVersion < 17]',
        'level': 'high',
        'description': '共享与其他应用程序在设备上,因此可以访问其他应用程序在设备上。它是保护许可不是分析中定义应用程序。因此,许可的保护水平应检查定义。如果它被设置为正常或危险,恶意的应用程序可以请求和获得许可和与组件交互。如果它被设置签名,只有应用程序使用相同的证书才能获得许可。',
        'name': 'is Protected by a permission, but the protection level of the permission should be checked.[Content Provider, targetSdkVersion < 17]'},
    'c_prot_normal_appl': {
        'title': '<strong>%s</strong> (%s) is Protected by a permission at the application level, but the protection level of the permission should be checked.</br>%s <br>[Content Provider, targetSdkVersion < 17]',
        'level': 'high',
        'description': '共享与其他应用程序在设备上,因此可以访问其他应用程序在设备上。它是允许在应用程序级别的保护。然而,权限设置的保护水平正常。这意味着一个恶意的应用程序可以请求并获得许可并与组件交互。如果是设置签名,只有应用程序使用相同的证书才能获得许可。',
        'name': 'is Protected by a permission at the application level, but the protection level of the permission should be checked.[Content Provider, targetSdkVersion < 17]'},
    'c_prot_danger_appl': {
        'title': '<strong>%s</strong> (%s) is Protected by a permission at the application level, but the protection level of the permission should be checked.</br>%s <br>[Content Provider, targetSdkVersion < 17]',
        'level': 'high',
        'description': '共享与其他应用程序在设备上,因此可以访问其他应用程序在设备上。它是允许在应用程序级别的保护。然而,保护级别的权限设置为危险。这意味着一个恶意的应用程序可以请求并获得许可并与组件交互。如果是设置签名,只有应用程序使用相同的证书才能获得许可。',
        'name': 'is Protected by a permission at the application level, but the protection level of the permission should be checked.[Content Provider, targetSdkVersion < 17]'},
    'c_prot_sign_appl': {
        'title': '<strong>%s</strong> (%s) is Protected by a permission at the application level.</br>%s <br>[Content Provider, targetSdkVersion < 17]',
        'level': 'info',
        'description': '共享与其他应用程序在设备上,因此可以访问其他应用程序在设备上。它是允许在应用程序级别的保护。',
        'name': 'is Protected by a permission at the application level.[Content Provider, targetSdkVersion < 17]'},
    'c_prot_sign_sys_appl': {
        'title': '<strong>%s</strong> (%s) is Protected by a permission at the application level, but the protection level of the permission should be checked.</br>%s <br>[Content Provider, targetSdkVersion < 17]',
        'level': 'info',
        'description': '找到出口,但允许在应用程序级别的保护。然而,权限设置为signatureOrSystem的保护水平。建议使用签名的水平。签名水平应该满足大多数场合,不依赖于设备上的应用程序安装。',
        'name': 'is Protected by a permission at the application level, but the protection level of the permission should be checked.[Content Provider, targetSdkVersion < 17]'},
    'c_prot_unknown_appl': {
        'title': '<strong>%s</strong> (%s) is Protected by a permission at application level, but the protection level of the permission should be checked.</br>%s <br>[Content Provider, targetSdkVersion < 17]',
        'level': 'high',
        'description': '共享与其他应用程序在设备上,因此可以访问其他应用程序在设备上。这是保护在应用程序级别不允许分析中定义应用程序。因此,许可的保护水平应检查定义。如果它被设置为正常或危险,恶意的应用程序可以请求和获得许可和与组件交互。如果它被设置签名,只有应用程序使用相同的证书才能获得许可。',
        'name': 'is Protected by a permission at application level, but the protection level of the permission should be checked.[Content Provider, targetSdkVersion < 17]'},
    'c_prot_normal_new': {
        'title': '<strong>%s</strong> (%s) is Protected by a permission, but the protection level of the permission should be checked if the application runs on a device where the the API level is less than 17</br>%s <br>[Content Provider, targetSdkVersion >= 17]',
        'level': 'high',
        'description': '将出口如果API的应用程序在设备上运行水平低于17。在这种情况下,它仍然受权限保护。然而,权限设置的保护水平正常。这意味着一个恶意的应用程序可以请求并获得许可并与组件交互。如果是设置签名,只有应用程序使用相同的证书才能获得许可。',
        'name': 'is Protected by a permission, but the protection level of the permission should be checked if the application runs on a device where the the API level is less than 17 [Content Provider, targetSdkVersion >= 17]'},
    'c_prot_danger_new': {
        'title': '<strong>%s</strong> (%s) is Protected by a permission, but the protection level of the permission should be checked if the application runs on a device where the API level is less than 17.</br>%s <br>[Content Provider, targetSdkVersion >= 17]',
        'level': 'high',
        'description': '内容提供者将出口如果API的应用程序在设备上运行水平低于17。在这种情况下,它仍然受权限保护。然而,保护级别的权限设置为危险。这意味着一个恶意的应用程序可以请求并获得许可并与组件交互。如果是设置签名,只有应用程序使用相同的证书才能获得许可。',
        'name': 'is Protected by a permission, but the protection level of the permission should be checked if the application runs on a device where the the API level is less than 17.[Content Provider, targetSdkVersion >= 17]'},
    'c_prot_sign_new': {
        'title': '<strong>%s</strong> (%s) is Protected by a permission.</br>%s <br>[Content Provider, targetSdkVersion >= 17]',
        'level': 'info',
        'description': '内容提供者将出口如果API的应用程序在设备上运行水平低于17。然而,受权限保护。',
        'name': 'is Protected by a permission.[Content Provider, targetSdkVersion >= 17]'}, 'c_prot_sign_sys_new': {
        'title': '<strong>%s</strong> (%s) is Protected by a permission, but the protection level of the permission should be checked.</br>%s <br>[Content Provider, targetSdkVersion >= 17]',
        'level': 'info',
        'description': '将出口如果应用程序运行在设备上的API级别还不到17岁。在这种情况下,它仍然受权限保护。然而,权限设置为signatureOrSystem的保护水平。建议使用签名的水平。签名水平应该满足大多数场合,不依赖于设备上的应用程序安装。',
        'name': 'is Protected by a permission, but the protection level of the permission should be checked.[Content Provider, targetSdkVersion >= 17]'},
    'c_prot_unknown_new': {
        'title': '<strong>%s</strong> (%s) is Protected by a permission, but the protection level of the permission should be checked  if the application runs on a device where the the API level is less than 17.</br>%s <br>[Content Provider, targetSdkVersion >= 17]',
        'level': 'high',
        'description': '将出口如果API的应用程序在设备上运行水平低于17。在这种情况下,它仍然是保护许可不分析中定义应用程序。因此,许可的保护水平应检查定义。如果它被设置为正常或危险,恶意的应用程序可以请求和获得许可和与组件交互。如果它被设置签名,只有应用程序使用相同的证书才能获得许可。',
        'name': 'is Protected by a permission, but the protection level of the permission should be checked  if the application runs on a device where the the API level is less than 17.[Content Provider, targetSdkVersion >= 17]'},
    'c_prot_normal_new_appl': {
        'title': '<strong>%s</strong> (%s) is Protected by a permission at the application level, but the protection level of the permission should be checked if the application runs on a device where the the API level is less than 17</br>%s <br>[Content Provider, targetSdkVersion >= 17]',
        'level': 'high',
        'description': '将出口如果API的应用程序在设备上运行水平低于17。在这种情况下,它仍然受权限保护。然而,权限设置的保护水平正常。这意味着一个恶意的应用程序可以请求并获得许可并与组件交互。如果是设置签名,只有应用程序使用相同的证书才能获得许可。',
        'name': 'is Protected by a permission at the application level should be checked, but the protection level of the permission if the application runs on a device where the the API level is less than 17.[Content Provider, targetSdkVersion >= 17]'},
    'c_prot_danger_new_appl': {
        'title': '<strong>%s</strong> (%s) is Protected by a permission at the application level, but the protection level of the permission should be checked if the application runs on a device where the the API level is less than 17.</br>%s <br>[Content Provider, targetSdkVersion >= 17]',
        'level': 'high',
        'description': '将出口如果API的应用程序在设备上运行水平低于17。在这种情况下,它仍然受权限保护。然而,保护级别的权限设置为危险。这意味着一个恶意的应用程序可以请求并获得许可并与组件交互。如果是设置签名,只有应用程序使用相同的证书才能获得许可。',
        'name': 'is Protected by a permission at the application level, but the protection level of the permission should be checked if the application runs on a device where the the API level is less than 17.[Content Provider, targetSdkVersion >= 17]'},
    'c_prot_sign_new_appl': {
        'title': '<strong>%s</strong> (%s) is Protected by a permission at the application level.</br>%s<br>[Content Provider, targetSdkVersion >= 17]',
        'level': 'info',
        'description': '内容提供者将出口如果API的应用程序在设备上运行水平低于17。然而,受权限保护。',
        'name': 'is Protected by a permission at the application level.[Content Provider, targetSdkVersion >= 17]'},
    'c_prot_sign_sys_new_appl': {
        'title': '<strong>%s</strong> (%s) is Protected by a permission at the application level, but the protection level of the permission should be checked.</br>%s <br>[Content Provider, targetSdkVersion >= 17]',
        'level': 'info',
        'description': '内容提供者将出口如果应用程序运行在设备上的API级别还不到17岁。在这种情况下,它仍然受权限保护。然而,权限设置为signatureOrSystem的保护水平。建议使用签名的水平。签名水平应该满足大多数场合,不依赖于设备上的应用程序安装。',
        'name': 'is Protected by a permission at the application level, but the protection level of the permission should be checked.[Content Provider, targetSdkVersion >= 17]'},
    'c_prot_unknown_new_appl': {
        'title': '<strong>%s</strong> (%s) is Protected by a permission at the application level, but the protection level of the permission should be checked  if the application runs on a device where the the API level is less than 17.</br>%s <br>[Content Provider, targetSdkVersion >= 17]',
        'level': 'high',
        'description': '内容提供者)将出口如果API的应用程序在设备上运行水平低于17。在这种情况下,它仍然是保护许可不分析中定义应用程序。因此,许可的保护水平应检查定义。如果它被设置为正常或危险,恶意的应用程序可以请求和获得许可和与组件交互。如果它被设置签名,只有应用程序使用相同的证书才能获得许可。',
        'name': 'is Protected by a permission at the application level, but the protection level of the permission should be checked  if the application runs on a device where the the API level is less than 17.[Content Provider, targetSdkVersion >= 17]'},
    'a_improper_provider': {'title': 'Improper Content Provider Permissions<br>[%s]', 'level': 'high',
                            'description': '一个内容提供者权限设置为允许访问其他应用程序在设备上。内容提供者可能包含敏感信息的应用程序,因此不应该共享。',
                            'name': 'Improper Content Provider Permissions'},
    'a_dailer_code': {'title': 'Dailer Code: %s Found <br>[android:scheme="android_secret_code"]', 'level': 'high',
                      'description': '发现了一个秘密代码清单。这些代码,当进入拨号器授权访问隐藏的内容可能包含敏感信息。',
                      'name': 'Dailer Code: Found <br>[android:scheme="android_secret_code"]'},
    'a_sms_receiver_port': {'title': 'Data SMS Receiver Set on Port: %s Found<br>[android:port]', 'level': 'high',
                            'description': '一个二进制SMS recevier配置为监听一个端口。二进制短信发送到设备处理的应用程序开发人员的任何方式的选择。这个短信的数据应该适当验证的应用程序。此外,应用程序应该假定短信接收来自一个不可信的来源。',
                            'name': 'Data SMS Receiver Set on Port: Found<br>[android:port]'},
    'a_high_intent_priority': {'title': 'High Intent Priority (%s)<br>[android:priority]', 'level': 'medium',
                               'description': '通过设置一个意图优先级高于另一个意图,应用有效地覆盖其他请求。',
                               'name': 'High Intent Priority [android:priority]'},
    'a_high_action_priority': {'title': 'High Action Priority (%s)<br>[android:priority] ', 'level': 'medium',
                               'description': '通过设置一个操作优先级高于另一个动作,应用有效地覆盖其他请求。',
                               'name': 'High Action Priority [android:priority]'}}
