# Androguard is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Androguard is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Androguard.  If not, see <http://www.gnu.org/licenses/>.

# frameworks/base/core/res/AndroidManifest.xml
# ######################################### PERMISSIONS ###################
# flake8: noqa
DVM_PERMISSIONS = {
    'MANIFEST_PERMISSION': {'SEND_SMS': ['dangerous', 'send SMS messages', '允许程序发送短信'],
                             'SEND_SMS_NO_CONFIRMATION': ['dangerous', 'send SMS messages', '允许程序发送短信'],
                             'CALL_PHONE': ['dangerous', 'directly call phone numbers', '允许程序从非系统拨号器里拨打电话'],
                             'RECEIVE_SMS': ['dangerous', 'receive SMS', '允许程序接收短信'],
                             'RECEIVE_MMS': ['dangerous', 'receive MMS', '允许程序接收彩信'],
                             'READ_SMS': ['dangerous', 'read SMS or MMS', '允许应用程序读取短信内容'],
                             'WRITE_SMS': ['dangerous', 'edit SMS or MMS', '允许应用程序编写短信'],
                             'RECEIVE_WAP_PUSH': ['dangerous', 'receive WAP', '允许程序接收WAP PUSH信息'],
                             'READ_CONTACTS': ['dangerous', 'read contact data', 'READ_CONTACTS'],
                             'WRITE_CONTACTS': ['dangerous', 'write contact data', 'WRITE_CONTACTS'],
                             'READ_PROFILE': ['dangerous', "read the user's personal profile data",
                                              '允许应用程序读取用户的个人资料信息'],
                             'WRITE_PROFILE': ['dangerous', "write the user's personal profile data",
                                               '允许应用程序编写用户的个人人资料信息，但不可读取'],
                             'READ_SOCIAL_STREAM': ['dangerous', "read from the user's social stream", '读取用户的社交信息流'],
                             'WRITE_SOCIAL_STREAM': ['dangerous', "write the user's social stream", '修改用户的社交信息流'],
                             'READ_CALENDAR': ['dangerous', 'read calendar events', '允许应用程序读取用户的日程信息'],
                             'WRITE_CALENDAR': ['dangerous', 'add or modify calendar events and send emails to guests',
                                                '允许程序写入日程，但不可读取'],
                             'READ_USER_DICTIONARY': ['dangerous', 'read user-defined dictionary', '允许应用程序读取用户字典'],
                             'WRITE_USER_DICTIONARY': ['normal', 'write to user-defined dictionary', '允许应用程序编写用户字典'],
                             'READ_HISTORY_BOOKMARKS': ['dangerous', "read Browser's history and bookmarks",
                                                        '允许应用程序读取浏览器收藏夹和历史记录'],
                             'WRITE_HISTORY_BOOKMARKS': ['dangerous', "write Browser's history and bookmarks",
                                                         '允许应用程序写入浏览器历史记录或收藏夹，但不可读取'],
                             'SET_ALARM': ['normal', 'set alarm in alarm clock', '允许程序设置闹铃提醒'],
                             'ACCESS_FINE_LOCATION': ['dangerous', 'fine (GPS) location', '允许通过GPS接收卫星的定位信息'],
                             'ACCESS_COARSE_LOCATION': ['dangerous', 'coarse (network-based) location',
                                                        '允许通过无线网络或移动基站的方式获取用户的经纬度信息'],
                             'ACCESS_MOCK_LOCATION': ['dangerous', 'mock location sources for testing',
                                                      '允许程序获取模拟定位信息，一般用于帮助开发者调试应用'],
                             'ACCESS_LOCATION_EXTRA_COMMANDS': ['normal', 'access extra location provider commands',
                                                                '允许程序访问额外的定位提供者指令'],
                             'INSTALL_LOCATION_PROVIDER': ['signatureOrSystem',
                                                           'permission to install a location provider', '允许程序安装定位提供'],
                             'INTERNET': ['dangerous', 'full Internet access', '允许程序访问网络连接，可能产生GPRS流量'],
                             'ACCESS_NETWORK_STATE': ['normal', 'view network status', '允许获取网络信息状态'],
                             'ACCESS_WIFI_STATE': ['normal', 'view Wi-Fi status', '允许获取当前WiFi接入的状态以及WLAN热点的信息'],
                             'BLUETOOTH': ['dangerous', 'create Bluetooth connections', '允许应用程序连接到蓝牙设备配对'],
                             'NFC': ['dangerous', 'control Near-Field Communication', '允许程序执行NFC近距离通讯操作'],
                             'USE_SIP': ['dangerous', 'make/receive Internet calls', '允许程序使用SIP视频服务'],
                             'ACCOUNT_MANAGER': ['signature', 'act as the Account Manager Service',
                                                 '允许程序通过账户验证方式访问账户管理ACCOUNT_MANAGER相关信息'],
                             'GET_ACCOUNTS': ['normal', 'discover known accounts', '允许访问的帐户的Gmail列表服务'],
                             'AUTHENTICATE_ACCOUNTS': ['dangerous', 'act as an account authenticator',
                                                       '允许一个应用程序添加语音邮件系统'],
                             'USE_CREDENTIALS': ['dangerous', 'use the authentication credentials of an account',
                                                 '允许应用程序请求验证AccountManager'],
                             'MANAGE_ACCOUNTS': ['dangerous', 'manage the accounts list', '允许程序管理AccountManager中的账户列表'],
                             'MODIFY_AUDIO_SETTINGS': ['dangerous', 'change your audio settings', '允许程序修改声音设置信息'],
                             'RECORD_AUDIO': ['dangerous', 'record audio', '允许程序录制声音通过手机或耳机的麦克'],
                             'CAMERA': ['dangerous', 'take pictures and videos', '允许程序访问摄像头进行拍照'],
                             'VIBRATE': ['normal', 'control vibrator', '允许程序振动'],
                             'FLASHLIGHT': ['normal', 'control flashlight', '允许访问的闪光灯'],
                             'ACCESS_USB': ['signatureOrSystem', 'access USB devices', '允许访问USB'],
                             'HARDWARE_TEST': ['signature', 'test hardware', '允许访问硬件辅助设备'],
                             'PROCESS_OUTGOING_CALLS': ['dangerous', 'intercept outgoing calls', '允许程序监视，修改或放弃播出电话'],
                             'MODIFY_PHONE_STATE': ['signatureOrSystem', 'modify phone status', '允许程序修改电话状态'],
                             'READ_PHONE_STATE': ['dangerous', 'read phone state and identity', '允许程序访问电话状态'],
                             'WRITE_EXTERNAL_STORAGE': ['dangerous', 'read/modify/delete SD card contents',
                                                        '允许程序写入外部存储'],
                             'READ_EXTERNAL_STORAGE': ['dangerous', 'read SD card contents', '允许应用程序读取设备外部存储空间的文件'],
                             'WRITE_SETTINGS': ['dangerous', 'modify global system settings', '允许应用程序读取或写入系统设置'],
                             'WRITE_SECURE_SETTINGS': ['signatureOrSystem', 'modify secure system settings',
                                                       '允许应用程序读取或写入安全系统设置'],
                             'WRITE_GSERVICES': ['signatureOrSystem', 'modify the Google services map',
                                                 '允许应用程序修改谷歌地图服务'],
                             'EXPAND_STATUS_BAR': ['normal', 'expand/collapse status bar', '允许应用程序展开或折叠状态栏'],
                             'GET_TASKS': ['dangerous', 'retrieve running applications', '允许应用程序获取当前的信息 或最近运行的任务'],
                             'REORDER_TASKS': ['dangerous', 'reorder applications running', '允许程序重新排序系统Z轴运行中的任务'],
                             'CHANGE_CONFIGURATION': ['dangerous', 'change your UI settings', '允许应用程序修改当前配置'],
                             'RESTART_PACKAGES': ['normal', 'kill background processes',
                                                  '允许程序结束任务通过restartPackage(String)方法，该方式将在外来放弃'],
                             'KILL_BACKGROUND_PROCESSES': ['normal', 'kill background processes',
                                                           '允许一个应用程序调用killBackgroundProcesses()方法结束后台进程'],
                             'FORCE_STOP_PACKAGES': ['signature', 'force-stop other applications',
                                                     '允许一个应用程序强制终止其他应用程序'],
                             'DUMP': ['signatureOrSystem', 'retrieve system internal status', '允许程序获取系统dump信息从系统服务'],
                             'SYSTEM_ALERT_WINDOW': ['dangerous', 'display system-level alerts', '允许程序显示系统窗口'],
                             'SET_ANIMATION_SCALE': ['dangerous', 'modify global animation speed', '允许程序设置全局动画缩放'],
                             'PERSISTENT_ACTIVITY': ['dangerous', 'make application always run',
                                                     '允许程序创建一个永久的Activity，该功能标记为将来将被移除'],
                             'GET_PACKAGE_SIZE': ['normal', 'measure application storage space',
                                                  '允许一个程序获取任何package占用空间容量'],
                             'SET_PREFERRED_APPLICATIONS': ['signature', 'set preferred applications', '允许程序设置应用的参数'],
                             'RECEIVE_BOOT_COMPLETED': ['normal', 'automatically start at boot', '允许程序开机自动运行'],
                             'BROADCAST_STICKY': ['normal', 'send sticky broadcast', '允许程序收到广播后快速收到下一个广播'],
                             'WAKE_LOCK': ['dangerous', 'prevent phone from sleeping', '允许程序在手机屏幕关闭后后台进程仍然运行'],
                             'SET_WALLPAPER': ['normal', 'set wallpaper', '允许程序设置桌面壁纸'],
                             'SET_WALLPAPER_HINTS': ['normal', 'set wallpaper size hints', '允许程序设置壁纸建议'],
                             'SET_TIME': ['signatureOrSystem', 'set time', '允许程序设置系统时间'],
                             'SET_TIME_ZONE': ['dangerous', 'set time zone', '允许程序设置系统时区'],
                             'MOUNT_UNMOUNT_FILESYSTEMS': ['dangerous', 'mount and unmount file systems',
                                                           '允许程序挂载、反挂载外部文件系统'],
                             'MOUNT_FORMAT_FILESYSTEMS': ['dangerous', 'format external storage', '允许程序格式化可移动文件系统'],
                             'ASEC_ACCESS': ['signature', 'get information on internal storage', '允许程序从内存中获取信息'],
                             'ASEC_CREATE': ['signature', 'create internal storage', '允许程序创建内存'],
                             'ASEC_DESTROY': ['signature', 'destroy internal storage', '允许程序销毁内存'],
                             'ASEC_MOUNT_UNMOUNT': ['signature', 'mount/unmount internal storage', '允许程序加载/卸载内存'],
                             'ASEC_RENAME': ['signature', 'rename internal storage', '允许程序对内存重命名'],
                             'DISABLE_KEYGUARD': ['dangerous', 'disable key lock', '允许应用程序禁用键盘锁'],
                             'READ_SYNC_SETTINGS': ['normal', 'read sync settings', '允许应用程序读取同步设置，读取Google在线同步设置'],
                             'WRITE_SYNC_SETTINGS': ['dangerous', 'write sync settings', '允许应用程序编写Google在线同步设置'],
                             'READ_SYNC_STATS': ['normal', 'read sync statistics', '允许程序读取同步状态，获得Google在线同步状态'],
                             'WRITE_APN_SETTINGS': ['dangerous', 'write Access Point Name settings',
                                                    '允许程序写入网络GPRS接入点设置'],
                             'SUBSCRIBED_FEEDS_READ': ['normal', 'read subscribed feeds', '允许应用程序访问已订阅的数据库'],
                             'SUBSCRIBED_FEEDS_WRITE': ['dangerous', 'write subscribed feeds', '允许应用程序写入或修改订阅内容的数据库'],
                             'CHANGE_NETWORK_STATE': ['dangerous', 'change network connectivity', '允许应用程序改变网络连接状态'],
                             'CHANGE_WIFI_STATE': ['dangerous', 'change Wi-Fi status', '允许应用程序改变wifi连接状态'],
                             'CHANGE_WIFI_MULTICAST_STATE': ['dangerous', 'allow Wi-Fi Multicast reception',
                                                             '允许应用程序进入无线多播模式'],
                             'BLUETOOTH_ADMIN': ['dangerous', 'bluetooth administration', '允许应用程序发现和蓝牙设备'],
                             'CLEAR_APP_CACHE': ['dangerous', 'delete all application cache data',
                                                 '允许应用程序清除所有已安装的 应用程序缓存'],
                             'READ_LOGS': ['dangerous', 'read sensitive log data', '允许应用程序读取系统底层日志'],
                             'SET_DEBUG_APP': ['dangerous', 'enable application debugging', '允许程序设置调试程序，一般用于开发'],
                             'SET_PROCESS_LIMIT': ['dangerous', 'limit number of running processes',
                                                   '允许程序设置最大的进程数量的限制'],
                             'SET_ALWAYS_FINISH': ['dangerous', 'make all background applications close',
                                                   '允许程序设置程序在后台是否总是退出'],
                             'SIGNAL_PERSISTENT_PROCESSES': ['dangerous', 'send Linux signals to applications',
                                                             '允许程序发送一个永久的进程信号'],
                             'DIAGNOSTIC': ['signature', 'read/write to resources owned by diag', '允许应用程序RW诊断资源'],
                             'STATUS_BAR': ['signatureOrSystem', 'disable or modify status bar', '允许程序打开、关闭、禁用状态栏'],
                             'STATUS_BAR_SERVICE': ['signature', 'status bar', '允许程序使用状态栏服务'],
                             'FORCE_BACK': ['signature', 'force application to close', '允许应用程序强制操作任何事情'],
                             'UPDATE_DEVICE_STATS': ['signatureOrSystem', 'modify battery statistics', '允许程序更新设备状态'],
                             'INTERNAL_SYSTEM_WINDOW': ['signature', 'display unauthorised windows',
                                                        '允许程序打开内部窗口，不对第三方应用程序开放此权限'],
                             'MANAGE_APP_TOKENS': ['signature', 'manage application tokens', '管理创建、摧毁、Z轴顺序，仅用于系统'],
                             'INJECT_EVENTS': ['signature', 'press keys and control buttons',
                                               '允许访问本程序的底层事件，获取按键、轨迹球的事件流'],
                             'SET_ACTIVITY_WATCHER': ['signature', 'monitor and control all application launching',
                                                      '设置Activity观察器一般用于monkey测试'],
                             'SHUTDOWN': ['signature', 'partial shutdown', '关闭activitymanager'],
                             'STOP_APP_SWITCHES': ['signature', 'prevent app switches', '防止用户切换应用'],
                             'READ_INPUT_STATE': ['signature', 'record what you type and actions that you take',
                                                  '读取当前键的输入状态，仅用于系统'],
                             'BIND_INPUT_METHOD': ['signature', 'bind to an input method',
                                                   '请求InputMethodService服务，只有系统才能使用'],
                             'BIND_WALLPAPER': ['signatureOrSystem', 'bind to wallpaper',
                                                '必须要求WallpaperService，以确保只有系统可以绑定到它'],
                             'BIND_DEVICE_ADMIN': ['signature', 'interact with device admin',
                                                   '请求系统管理员接收者receiver，只有系统才能使用'],
                             'SET_ORIENTATION': ['signature', 'change screen orientation', '设置屏幕方向为横屏或标准方式显示，不用于普通应用'],
                             'INSTALL_PACKAGES': ['signatureOrSystem', 'directly install applications', '允许程序安装应用'],
                             'REQUEST_INSTALL_PACKAGES': ['dangerous',
                                                          'Allows an application to request installing packages.',
                                                          '允许程序访问已安装应用列表'],
                             'CLEAR_APP_USER_DATA': ['signature', "delete other applications' data", '允许应用程序清除用户数据'],
                             'DELETE_CACHE_FILES': ['signatureOrSystem', "delete other applications' caches",
                                                    '允许应用程序删除缓存文件'],
                             'DELETE_PACKAGES': ['signatureOrSystem', 'delete applications', '允许应用程序删除应用'],
                             'MOVE_PACKAGE': ['signatureOrSystem', 'Move application resources', '允许程序导入/导出资源'],
                             'CHANGE_COMPONENT_ENABLED_STATE': ['signatureOrSystem',
                                                                'enable or disable application components',
                                                                '允许一个应用程序改变组件是否启用状态'],
                             'ACCESS_SURFACE_FLINGER': ['signature', 'access SurfaceFlinger',
                                                        'Android平台上底层的图形显示支持，一般用于游戏或照相机预览界面和底层模式的屏幕截图'],
                             'READ_FRAME_BUFFER': ['signature', 'read frame buffer', '允许程序读取帧缓存用于屏幕截图'],
                             'BRICK': ['signature', 'permanently disable phone', '能够禁用手机，非常危险，顾名思义就是让手机变成砖头'],
                             'REBOOT': ['signatureOrSystem', 'force phone reboot', '允许能够重新启动设备'],
                             'DEVICE_POWER': ['signature', 'turn phone on or off', '允许低级访问电源管理'],
                             'FACTORY_TEST': ['signature', 'run in factory test mode', '允许程序运行工厂测试模式'],
                             'BROADCAST_PACKAGE_REMOVED': ['signature', 'send package removed broadcast',
                                                           '允许应用程序广播通知应用程序包被移除后'],
                             'BROADCAST_SMS': ['signature', 'send SMS-received broadcast', '允许程序当收到短信时触发一个广播'],
                             'BROADCAST_WAP_PUSH': ['signature', 'send WAP-PUSH-received broadcast',
                                                    '允许应用程序播放一个WAP推收到通知'],
                             'MASTER_CLEAR': ['signatureOrSystem', 'reset system to factory defaults',
                                              '允许程序执行软格式化，删除系统配置信息'],
                             'CALL_PRIVILEGED': ['signatureOrSystem', 'directly call any phone numbers',
                                                 '允许程序拨打电话，替换系统的拨号器界面'],
                             'PERFORM_CDMA_PROVISIONING': ['signatureOrSystem', 'directly start CDMA phone setup',
                                                           '允许程序开启CDMA配置'],
                             'CONTROL_LOCATION_UPDATES': ['signatureOrSystem', 'control location update notifications',
                                                          '允许程序获得移动网络定位信息改变'],
                             'ACCESS_CHECKIN_PROPERTIES': ['signatureOrSystem', 'access check-in properties',
                                                           '允许读取或写入登记check-in数据库属性表的权限'],
                             'PACKAGE_USAGE_STATS': ['signature', 'update component usage statistics',
                                                     '允许对收集到的组件使用数据的修改'],
                             'BATTERY_STATS': ['normal', 'modify battery statistics', '允许获取电池电量统计信息'],
                             'BACKUP': ['signatureOrSystem', 'control system back up and restore', '允许程序控制系统的备份恢复机制'],
                             'BIND_APPWIDGET': ['signatureOrSystem', 'choose widgets',
                                                '允许应用程序告诉AppWidget服务应用程序可以访问AppWidget的数据'],
                             'CHANGE_BACKGROUND_DATA_SETTING': ['signature', 'change background data usage setting',
                                                                '允许程序修改后台数据使用设置'],
                             'GLOBAL_SEARCH': ['signatureOrSystem', '', '允许程序允许全局搜索'],
                             'GLOBAL_SEARCH_CONTROL': ['signature', ''],
                             'SET_WALLPAPER_COMPONENT': ['signatureOrSystem', ''],
                             'ACCESS_CACHE_FILESYSTEM': ['signatureOrSystem', 'access the cache file system',
                                                         '允许程序读写缓存文件系统'], 'COPY_PROTECTED_DATA': ['signature',
                                                                                                  'Allows to invoke default container service to copy content. Not for use by common applications.',
                                                                                                  '允许拷贝容器数据'],
                             'C2D_MESSAGE': ['signature', 'Allows cloud to device messaging', '允许程序接收推送'],
                             'RECEIVE': ['signature', 'C2DM permissions', '允许推送'],
                             'ADD_VOICEMAIL': ['dangerous', 'add voicemails into the system', '允许一个应用程序添加语音邮件系统'],
                             'ACCEPT_HANDOVER': ['dangerous', '', '允许当前程序继续调用另一个程序'],
                             'ACCESS_NOTIFICATION_POLICY': ['normal', '', '允许访问通知策略的应用程序的标记许可'],
                             'ANSWER_PHONE_CALLS': ['dangerous', '', '允许接听来电'],
                             'BIND_ACCESSIBILITY_SERVICE': ['signature', '', '请求accessibilityservice服务，以确保只有系统可以绑定到它'],
                             'BIND_AUTOFILL_SERVICE': ['signature', '', '自动填充服务权限'],
                             'BIND_CARRIER_MESSAGING_SERVICE': ['normal', '',
                                                                '这个常数是在API级别23否决。 使用BIND_CARRIER_SERVICES替代'],
                             'BIND_CARRIER_SERVICES': ['signature', '', '允许在载体应用程序中绑定服务的系统进程将有此权限。'],
                             'BIND_CHOOSER_TARGET_SERVICE': ['signature', '',
                                                             '必须由ChooserTargetService要求，确保只有系统可以绑定到它。'],
                             'BIND_CONDITION_PROVIDER_SERVICE': ['signature', '',
                                                                 '必须由ConditionProviderService要求，确保只有系统可以绑定到它。'],
                             'BIND_DREAM_SERVICE': ['signature', '', '屏保服务权限'],
                             'BIND_INCALL_SERVICE': ['signature', '', '电话服务权限'],
                             'BIND_MIDI_DEVICE_SERVICE': ['signature', '', '音视频服务权限'],
                             'BIND_NFC_SERVICE': ['signature', '', '由HostApduService或OffHostApduService，必须确保只有系统绑定到它'],
                             'BIND_NOTIFICATION_LISTENER_SERVICE': ['signature', '',
                                                                    '必须要求由NotificationListenerService，以确保只有系统可以绑定到它'],
                             'BIND_PRINT_SERVICE': ['signature', '', '必须要求由PrintService，以确保只有系统可以绑定到它'],
                             'BIND_QUICK_SETTINGS_TILE': ['normal', '', '允许应用程序绑定到第三方快速设置瓷砖。'],
                             'BIND_REMOTEVIEWS': ['normal', '', '必须通过RemoteViewsService，服务来请求，只有系统才能用'],
                             'BIND_SCREENING_SERVICE': ['signature', '', '必须由CallScreeningService要求，确保只有系统可以绑定到它。'],
                             'BIND_TELECOM_CONNECTION_SERVICE': ['signature', '',
                                                                 '必须由ConnectionService要求，确保只有系统可以绑定到它。'],
                             'BIND_TEXT_SERVICE': ['signature', '', '必须要求TextService，以确保只有系统可以绑定到它'],
                             'BIND_TV_INPUT': ['signature', '', '必须由TvInputService 需要确保只有系统可以绑定到它。'],
                             'BIND_VISUAL_VOICEMAIL_SERVICE': ['signature', '',
                                                               '必须由VisualVoicemailService要求，确保只有系统可以绑定到它。'],
                             'BIND_VOICE_INTERACTION': ['signature', '', '必须由VoiceInteractionService要求，确保只有系统可以绑定到它。'],
                             'BIND_VPN_SERVICE': ['signature', '', '必须要求VpnService，以确保只有系统可以绑定到它'],
                             'BIND_VR_LISTENER_SERVICE': ['signature', '', '必须由一个VrListenerService要求，确保只有系统可以绑定到它。'],
                             'BLUETOOTH_PRIVILEGED': ['normal', '', '允许应用程序对蓝牙设备，不需要用户交互'],
                             'BODY_SENSORS': ['dangerous', '', '允许应用程序访问用户使用的传感器来测量'],
                             'CAPTURE_AUDIO_OUTPUT': ['normal', '', '允许应用程序捕获音频输出'],
                             'CAPTURE_SECURE_VIDEO_OUTPUT': ['normal', '', '允许应用程序获取安全的视频输出'],
                             'CAPTURE_VIDEO_OUTPUT': ['normal', '', '允许一个应用程序来捕获视频输出'],
                             'FOREGROUND_SERVICE': ['normal', '', '允许程序使用前台启动服务'],
                             'GET_ACCOUNTS_PRIVILEGED': ['normal', '', '允许访问帐户服务中的帐户列表。'],
                             'INSTALL_SHORTCUT': ['normal', '', '允许应用程序快捷方式'],
                             'INSTANT_APP_FOREGROUND_SERVICE': ['normal', '', '允许程序创建前台服务'],
                             'LOCATION_HARDWARE': ['normal', '', '允许一个应用程序中使用定位功能的硬件，不使用第三方应用'],
                             'MANAGE_DOCUMENTS': ['signature', '', '允许程序管理文件的访问'],
                             'MANAGE_OWN_CALLS': ['normal', '', '允许程序处理自身调用'],
                             'MEDIA_CONTENT_CONTROL': ['normal', '', '允许一个应用程序知道什么是播放和控制其内容 ,不能被第三方应用使用'],
                             'NFC_TRANSACTION_EVENT': ['normal', '', '允许程序接收NFC处理事件'],
                             'READ_CALL_LOG': ['dangerous', '', '允许应用程序读取用户的通话记录'],
                             'READ_PHONE_NUMBERS': ['dangerous', '', '允许读取设备的电话号码'],
                             'READ_VOICEMAIL': ['signature', '', '允许应用程序在系统读取语音邮件。'],
                             'REQUEST_COMPANION_RUN_IN_BACKGROUND': ['normal', '', '允许后台运行配套应用程序'],
                             'REQUEST_COMPANION_USE_DATA_IN_BACKGROUND': ['normal', '', '允许配套应用程序在后台使用数据'],
                             'REQUEST_DELETE_PACKAGES': ['normal', '', '允许应用程序请求删除软件包'],
                             'REQUEST_IGNORE_BATTERY_OPTIMIZATIONS': ['normal', '',
                                                                      '权限的应用程序必须要使用 ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS。'],
                             'SEND_RESPOND_VIA_MESSAGE': ['normal', '', '允许用户在来电的时候用你的应用进行即时的短信息回复'],
                             'TRANSMIT_IR': ['normal', '', '允许使用设备的红外发射器，如果可用'],
                             'UNINSTALL_SHORTCUT': ['normal', '', '删除快捷方式'],
                             'USE_BIOMETRIC': ['normal', '', '允许应用程序使用生物识别技术'],
                             'USE_FINGERPRINT': ['normal', 'allow use of fingerprint', '允许应用程序使用指纹硬件。'],
                             'WRITE_CALL_LOG': ['dangerous', '', '允许程序写入联系人数据，但不可读取'],
                             'WRITE_VOICEMAIL': ['signature', '', '允许应用程序修改和删除系统中的现有的语音邮件。'],
                             'ACCESS_BACKGROUND_LOCATION': ['dangerous', 'access location in background', '允许应用程序后台定位'],
                             'ACCESS_MEDIA_LOCATION': ['dangerous', 'access any geographic locations', '查看照片的地理位置信息'],
                             'ACTIVITY_RECOGNITION': ['dangerous', 'allow application to recognize physical activity',
                                                      '允许应用程序识别物理活动'],
                             'BIND_CALL_REDIRECTION_SERVICE': ['signature', '',
                                                               '必须由CallRedirectionService要求，确保只有系统可以绑定到它。'],
                             'BIND_CARRIER_MESSAGING_CLIENT_SERVICE': ['signature', '',
                                                                       'CarrierMessagingClientService的子类需要的权限'],
                             'CALL_COMPANION_APP': ['normal', '', '允许实现InCallService API的app成为配套应用程序'],
                             'REQUEST_PASSWORD_COMPLEXITY': ['normal', '', '允许程序读取锁屏等级并提示用户提升等级'],
                             'SMS_FINANCIAL_TRANSACTIONS': ['signature',
                                                            'Allows financial apps to read filtered sms messages',
                                                            '允许金融类app读取过滤后的短信'],
                             'START_VIEW_PERMISSION_USAGE': ['signature', '', '允许应用弹出权限提示框'],
                             'USE_FULL_SCREEN_INTENT': ['normal', '', '允许Build.VERSION_CODES.Q应用使用全屏intents。'],
                             'ACCESS_CALL_AUDIO': ['signature', 'Application can access call audio',
                                                   '允许分配给Dialer角色的应用程序被授予对TX和RX电话呼叫音频流的访问权限。'],
                             'BIND_CONTROLS': ['normal', 'Allows SystemUI to request third party controls.',
                                               '允许SystemUI请求第三方控件。'],
                             'BIND_QUICK_ACCESS_WALLET_SERVICE': ['signature', '',
                                                                  '必须由a QuickAccessWalletService 来要求，以确保只有系统可以绑定到它。'],
                             'INTERACT_ACROSS_PROFILES': ['normal', '', '允许跨同一个人资料组中的个人资料进行交互。'],
                             'LOADER_USAGE_STATS': ['signature', '', '允许数据加载器读取程序包的访问日志。'],
                             'MANAGE_EXTERNAL_STORAGE': ['dangerous',
                                                         'Allows an application a broad access to external storage in scoped storage',
                                                         '允许应用程序广泛访问作用域存储中的外部存储。'],
                             'NFC_PREFERRED_PAYMENT_INFO': ['normal', '', '允许应用程序接收NFC首选付款服务信息。'],
                             'QUERY_ALL_PACKAGES': ['dangerous', '', '允许查询设备上任何正常的应用程序，而不管清单声明如何。'],
                             'READ_PRECISE_PHONE_STATE': ['normal', '', '允许只读访问精确的电话状态。']},
    'MANIFEST_PERMISSION_GROUP': {
         'ACCOUNTS': 'Permissions for direct access to the accounts managed by the Account Manager.',
         'COST_MONEY': 'Used for permissions that can be used to make the user spend money without their direct involvement.',
         'DEVELOPMENT_TOOLS': 'Group of permissions that are related to development features.',
         'HARDWARE_CONTROLS': 'Used for permissions that provide direct access to the hardware on the device.',
         'LOCATION': "Used for permissions that allow access to the user's current location.",
         'MESSAGES': 'Used for permissions that allow an application to send messages on behalf of the user or intercept messages being received by the user.',
         'NETWORK': 'Used for permissions that provide access to networking services.',
         'PERSONAL_INFO': "Used for permissions that provide access to the user's private data, such as contacts, calendar events, e-mail messages, etc.",
         'PHONE_CALLS': 'Used for permissions that are associated with accessing and modifyign telephony state: intercepting outgoing calls, reading and modifying the phone state.',
         'STORAGE': 'Group of permissions that are related to SD card access.',
         'SYSTEM_TOOLS': 'Group of permissions that are related to system APIs.'},
}

